In [1]:
import numpy as np

In [2]:
arr = np.array([[[1.8,2,3],[4,2,5]],[[3,2,1],[5,2,4]]])

In [3]:
print("Array is of type : ",type(arr))

Array is of type :  <class 'numpy.ndarray'>


In [4]:
print("No. of dimensions : ",arr.ndim)

No. of dimensions :  3


In [5]:
print("shape of array : ",arr.shape)

shape of array :  (2, 2, 3)


In [6]:
print("size of array : ",arr.size)

size of array :  12


In [7]:
print("Array stores elements of type : ",arr.dtype)

Array stores elements of type :  float64


In [8]:
a = np.array([[1,2,4],[5,8,7]], dtype = 'float')

In [9]:
print("Array created passes list : \n",a)

Array created passes list : 
 [[1. 2. 4.]
 [5. 8. 7.]]


In [10]:
b = np.array((1,2,3))

In [11]:
print("Array created using passed tuple : \n",b)

Array created using passed tuple : 
 [1 2 3]


In [12]:
c = np.zeros((3,4))

In [15]:
print("Array intialized with all zeros : \n",c)

Array intialized with all zeros : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [16]:
d = np.full((3,3),6,dtype = 'complex')

In [17]:
print("Array initialized with all 6s. Array type is complex : \n",d)

Array initialized with all 6s. Array type is complex : 
 [[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]


In [18]:
e = np.random.randint((2,2))

In [19]:
print("Random array :\n",e)

Random array :
 [1 0]


In [20]:
f = np.arange(0,30,5)

In [21]:
print("A sequential array with steps : \n",f)

A sequential array with steps : 
 [ 0  5 10 15 20 25]


In [22]:
g = np.linspace(0,5,10)

In [23]:
print("Sequential array with 10mvalues between 0 and 5 : \n",g)

Sequential array with 10mvalues between 0 and 5 : 
 [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [24]:
arr = np.array([[1,2,3,4],[5,2,4,2],[1,2,0,1]])

In [25]:
newarr = arr.reshape(2,2,3)

In [26]:
print("\n Original Array : \n",arr)
print("\n Reshaped array : \n",newarr)


 Original Array : 
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]

 Reshaped array : 
 [[[1 2 3]
  [4 5 2]]

 [[4 2 1]
  [2 0 1]]]


In [27]:
arr = np.array([[1,2,3],[4,5,6]])

In [29]:
flatten_array = arr.flatten()

In [30]:
print("\n Original Array : \n",arr)
print("\n Reshaped array : \n",flatten_array)


 Original Array : 
 [[1 2 3]
 [4 5 6]]

 Reshaped array : 
 [1 2 3 4 5 6]


In [31]:
arr = np.array([[-1,2,0,4],[4,-0.5,6,0],[2.6,0,7,8],[3,-7,4,2.0]])

In [32]:
temp = arr[:2,::2]
print("Array with first 2 rows and alternate columns (0 and 2) : \n",temp)

Array with first 2 rows and alternate columns (0 and 2) : 
 [[-1.  0.]
 [ 4.  6.]]


In [33]:
temp = arr[[0,1,2,3],[3,2,1,0]]
print("Elements at indices (0,3),(1,2),(2,1),(3,0) : \n",temp)

Elements at indices (0,3),(1,2),(2,1),(3,0) : 
 [4. 6. 0. 3.]


In [34]:
cond = arr > 0
temp = arr[cond]
print("Elements greater than 0 : \n",temp)

Elements greater than 0 : 
 [2.  4.  4.  6.  2.6 7.  8.  3.  4.  2. ]


In [36]:
a = np.array([1,2,5,3])
print("Adding 1 to every element : ",a+1)
print("Substracting 3 from each element : ",a-3)
print("Multiplying each element by 10 : ",a*3)
print("Squaring each element : ",a**2)
a*=2
print("Doubled each element of original array : ",a)

Adding 1 to every element :  [2 3 6 4]
Substracting 3 from each element :  [-2 -1  2  0]
Multiplying each element by 10 :  [ 3  6 15  9]
Squaring each element :  [ 1  4 25  9]
Doubled each element of original array :  [ 2  4 10  6]


In [37]:
a = np.array([[1,2,3],[3,4,5],[9,6,0]])
print("\n Original array : \n",a)
print("Transpose of array : \n",a.T)


 Original array : 
 [[1 2 3]
 [3 4 5]
 [9 6 0]]
Transpose of array : 
 [[1 3 9]
 [2 4 6]
 [3 5 0]]


In [38]:
arr = np.array([[1,5,6],[4,7,2],[3,1,9]])

In [39]:
print("Largest element is : ",arr.max())
print("Row-wise maximum elements ",arr.max(axis = 1))
print("Column-wise minimum elements ",arr.min(axis = 0))
print("Sum of all array elemnts",arr.sum())
print("Cummulative sum along each row : \n",arr.cumsum(axis = 1))

Largest element is :  9
Row-wise maximum elements  [6 7 9]
Column-wise minimum elements  [1 1 2]
Sum of all array elemnts 38
Cummulative sum along each row : 
 [[ 1  6 12]
 [ 4 11 13]
 [ 3  4 13]]


In [ ]:
a = np.array([[1,2],[3,4]])
b = np.arrar([[4,3],[2,1]])

In [40]:
print("Array sum : \n",a + b)
print("Array multiplication : \n", a * b)
print("MAtrix multiplication : \n",a.dot(b))

Array sum : 
 [[ 2  4  6]
 [ 4  6  8]
 [10  8  3]]
Array multiplication : 
 [[ 1  4  9]
 [ 3  8 15]
 [ 9 12  0]]
MAtrix multiplication : 
 [14 26 21]
