In [1]:
import numpy as np

In [2]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.linspace(1,26,3)

array([ 1. , 13.5, 26. ])

In [6]:
np.indices((3,3))

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

In [7]:
np.random.rand()

0.22252650597634627

In [8]:
np.random.rand(3,2)

array([[0.54676976, 0.7437499 ],
       [0.39487861, 0.78447281],
       [0.91371908, 0.78451304]])

In [9]:
arr = np.arange(10)
np.random.shuffle(arr)
print(arr)

[2 1 0 5 3 4 6 7 8 9]
